version: "3.9"
   
services:
  mongo:
    image: mongo:4.4.17  # Computerome runs 4.2.8
    ports:
      - "27107:27017"
    volumes:
      - ./dumps:/mnt/dumps
  
  scripts:
    build: .
    environment:
      - "BIFROST_DB_KEY=mongodb://mongo:27017/bifrost_test"
    depends_on:
      - mongo
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000", "--reload"]
    
